/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2014-08-26 13:14:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.site;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t    <div class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("        \t<div class=\"navbar-inner\">\r\n");
      out.write("\t            <button type=\"button\" class=\"navbar-toggle pull-left animated flip\">\r\n");
      out.write("\t                <span class=\"sr-only\"></span>\r\n");
      out.write("\t                <span class=\"icon-bar\"></span>\r\n");
      out.write("\t                <span class=\"icon-bar\"></span>\r\n");
      out.write("\t                <span class=\"icon-bar\"></span>\r\n");
      out.write("\t            </button>\r\n");
      out.write("\t            \r\n");
      out.write("\t            <a class=\"navbar-brand\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t                <img alt=\"Logo\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" class=\"hidden-xs\"/> \r\n");
      out.write("\t                <span>");
      if (_jspx_meth_f_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\r\n");
      out.write("\t            <div class=\"btn-group pull-right\">\r\n");
      out.write("\t                <button class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t                    <i class=\"glyphicon glyphicon-user\"></i><span class=\"hidden-sm hidden-xs\"> ");
      if (_jspx_meth_f_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t                    <span class=\"caret\"></span>\r\n");
      out.write("\t                </button>\r\n");
      out.write("\t                <ul class=\"dropdown-menu\">\r\n");
      out.write("\t                    <li><a href=\"#\">");
      if (_jspx_meth_f_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("</a></li>\r\n");
      out.write("\t                    <li class=\"divider\"></li>\r\n");
      out.write("\t                    <li><a href=\"login.html\">");
      if (_jspx_meth_f_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("</a></li>\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            <ul class=\"collapse navbar-collapse nav navbar-nav top-menu\">\r\n");
      out.write("\t                <li><a href=\"#\"> ");
      if (_jspx_meth_f_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("</a></li>               \r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <form class=\"navbar-search pull-left\">\r\n");
      out.write("\t                        <input type=\"text\" placeholder=\"");
      if (_jspx_meth_f_005fmessage_005f5(_jspx_page_context))
        return;
      out.write("\" class=\"search-query form-control col-md-10\">\r\n");
      out.write("\t                    </form>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t               \r\n");
      out.write("\t            </ul>\t\t\t\t\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        \r\n");
      out.write("\t    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/jsp/site/header.jsp(16,43) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/jsp/site/header.jsp(17,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/imagens/icon.png");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_f_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_f_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_f_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005fmessage_005f0.setParent(null);
    // /WEB-INF/jsp/site/header.jsp(18,23) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005fmessage_005f0.setKey("site");
    int _jspx_eval_f_005fmessage_005f0 = _jspx_th_f_005fmessage_005f0.doStartTag();
    if (_jspx_th_f_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_f_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_f_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_f_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_f_005fmessage_005f1.setParent(null);
    // /WEB-INF/jsp/site/header.jsp(23,96) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005fmessage_005f1.setKey("menu.entrar");
    int _jspx_eval_f_005fmessage_005f1 = _jspx_th_f_005fmessage_005f1.doStartTag();
    if (_jspx_th_f_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_f_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_f_005fmessage_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_f_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_f_005fmessage_005f2.setParent(null);
    // /WEB-INF/jsp/site/header.jsp(27,37) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005fmessage_005f2.setKey("menu.login");
    int _jspx_eval_f_005fmessage_005f2 = _jspx_th_f_005fmessage_005f2.doStartTag();
    if (_jspx_th_f_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_f_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_f_005fmessage_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_f_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_f_005fmessage_005f3.setParent(null);
    // /WEB-INF/jsp/site/header.jsp(29,46) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005fmessage_005f3.setKey("menu.cadastrar");
    int _jspx_eval_f_005fmessage_005f3 = _jspx_th_f_005fmessage_005f3.doStartTag();
    if (_jspx_th_f_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f3);
    return false;
  }

  private boolean _jspx_meth_f_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_f_005fmessage_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_f_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_f_005fmessage_005f4.setParent(null);
    // /WEB-INF/jsp/site/header.jsp(34,34) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005fmessage_005f4.setKey("menu.quem.somos");
    int _jspx_eval_f_005fmessage_005f4 = _jspx_th_f_005fmessage_005f4.doStartTag();
    if (_jspx_th_f_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f4);
    return false;
  }

  private boolean _jspx_meth_f_005fmessage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_f_005fmessage_005f5 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_f_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_f_005fmessage_005f5.setParent(null);
    // /WEB-INF/jsp/site/header.jsp(37,57) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005fmessage_005f5.setKey("menu.pesquisar");
    int _jspx_eval_f_005fmessage_005f5 = _jspx_th_f_005fmessage_005f5.doStartTag();
    if (_jspx_th_f_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_f_005fmessage_005f5);
    return false;
  }
}
